# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Brfit < Formula
  desc "AI 코딩 어시스턴트를 위한 코드 브리핑 도구"
  homepage "https://github.com/indigo-net/Brf.it"
  version "0.10.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/indigo-net/Brf.it/releases/download/v0.10.0/Brf.it_0.10.0_darwin_amd64.tar.gz"
      sha256 "a60c1590bbfd627d984aac2fa3eae54d176c44b5f0f0ce0598ca935e0910fd13"

      def install
        bin.install "brfit"
      end
    end
    on_arm do
      url "https://github.com/indigo-net/Brf.it/releases/download/v0.10.0/Brf.it_0.10.0_darwin_arm64.tar.gz"
      sha256 "0f759c28e76131c2cf8bca3a51b335730bf16213d55220962c6aff14ad5a22ca"

      def install
        bin.install "brfit"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/indigo-net/Brf.it/releases/download/v0.10.0/Brf.it_0.10.0_linux_amd64.tar.gz"
        sha256 "ff065c8ee6af9cc7ad80b11b951f74ded10650c0225e874719c1998cb209a13a"

        def install
          bin.install "brfit"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/indigo-net/Brf.it/releases/download/v0.10.0/Brf.it_0.10.0_linux_arm64.tar.gz"
        sha256 "179b2fa37d29a2f5b5acbea68b808d8e474dbbad775269c3732f0cc06ac6e1da"

        def install
          bin.install "brfit"
        end
      end
    end
  end

  test do
    system "#{bin}/brfit", "--version"
  end
end
