# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Brfit < Formula
  desc "AI 코딩 어시스턴트를 위한 코드 브리핑 도구"
  homepage "https://github.com/indigo-net/Brf.it"
  version "0.13.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/indigo-net/Brf.it/releases/download/v0.13.0/Brf.it_0.13.0_darwin_amd64.tar.gz"
      sha256 "eefd1ff5ec35b36a618962b472a8abb1eddb30b8bb518d2314119a90d3e37a2b"

      def install
        bin.install "brfit"
      end
    end
    on_arm do
      url "https://github.com/indigo-net/Brf.it/releases/download/v0.13.0/Brf.it_0.13.0_darwin_arm64.tar.gz"
      sha256 "fc6d131581e0153e877f7f78b7a6775e7ccb2cd5ce0ba4bf87a83b9083938e81"

      def install
        bin.install "brfit"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/indigo-net/Brf.it/releases/download/v0.13.0/Brf.it_0.13.0_linux_amd64.tar.gz"
        sha256 "99c4613a6779e16182bca04ff2ee947ee3d702f4d594a503b51f25f240677fc2"

        def install
          bin.install "brfit"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/indigo-net/Brf.it/releases/download/v0.13.0/Brf.it_0.13.0_linux_arm64.tar.gz"
        sha256 "90498f297bd8150bab77e69ceb4aa77bc5b72224612f551addb509b18203bf17"

        def install
          bin.install "brfit"
        end
      end
    end
  end

  test do
    system "#{bin}/brfit", "--version"
  end
end
